# Generated by Django 4.1.3 on 2022-11-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "firm_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("country", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "form_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Med",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "med_firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.firm"
                    ),
                ),
                (
                    "med_form_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(max_length=50, unique=True)),
                ("prescription", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescription_number", models.IntegerField()),
                ("patient_full_name", models.CharField(max_length=60)),
                ("med_policy", models.IntegerField()),
                ("release_date", models.DateField()),
                ("amount", models.IntegerField()),
                (
                    "med_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.med"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="med",
            name="med_name",
            field=models.ForeignKey(
                db_column="med_name",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.medslist",
                to_field="med_name",
            ),
        ),
    ]
