# Generated by Django 4.1.3 on 2022-11-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medslist",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
